#Site settings
title: "Sample Site"
email: owen@ostillman.co.uk
description: "Skill // Siill // Skill"
# Build settings

markdown: kramdown
permalink: pretty

port: 3000
host: 0.0.0.0

sass:
  sass_dir: assets/css
  style: :nested